# Generated by Django 5.0.4 on 2026-04-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(check=models.Q(('line_total__gte', 0)), name='order_item_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(check=models.Q(('valid_until__gt', models.F('valid_from'))), name='promo_valid_window_check'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.CheckConstraint(check=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='promo_discount_percentage_range_check'),
        ),
    ]
