# Generated by Django 5.0.4 on 2026-03-27 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField()),
                ('top_notes', models.CharField(blank=True, help_text='Comma-separated, e.g. Rose, Saffron, Bergamot', max_length=300)),
                ('heart_notes', models.CharField(blank=True, max_length=300)),
                ('base_notes', models.CharField(blank=True, help_text='e.g. Oud, Musk, Amber, Sandalwood', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='atar/covers/')),
                ('search_vector_json', models.JSONField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'atar',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=550, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('translator', models.CharField(blank=True, max_length=200, null=True)),
                ('publisher', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('EN', 'English'), ('UR', 'Urdu'), ('AR', 'Arabic'), ('BN', 'Bengali')], max_length=2)),
                ('script_type', models.CharField(choices=[('AR', 'Arabic Script'), ('RM', 'Roman Script'), ('UR', 'Urdu Script')], max_length=2)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('format', models.CharField(choices=[('HB', 'Hardcover'), ('PB', 'Paperback'), ('LB', 'Leather-bound')], max_length=2)),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='books/covers/')),
                ('search_vector_json', models.JSONField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'books',
                'indexes': [models.Index(fields=['slug'], name='books_slug_0d7beb_idx'), models.Index(fields=['language', 'script_type'], name='books_languag_e2f838_idx'), models.Index(fields=['is_active'], name='books_is_acti_a3aae1_idx'), models.Index(fields=['price'], name='books_price_89e2a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='AtarVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_ml', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('atar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.atar')),
            ],
            options={
                'db_table': 'atar_variants',
                'indexes': [models.Index(fields=['sku'], name='atar_varian_sku_f0c810_idx')],
                'unique_together': {('atar', 'volume_ml')},
            },
        ),
    ]
